name : Test Workflow
on   : push
jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: list file
        run: ls
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Checking node version
        run: node -v
      - name: starting test
        run: npm run test
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: list file
        run: ls
      - name: Setup node
        uses: actions/setup-node@v4
      - name: install dependencies
        run: npm install
      - name: starting test
        run: npm run test
      - name: start server
        run: node server.js
      - name: deploy-step
        
        
        
  
      
  say-bye:
    needs: say-hello
    runs-on: ubuntu-latest

    steps:
      - name: Print message 
        run: echo "Bye , github Actions!!!!"

#   By default jobs run parallely
# To run them in sequence we use needs

# runners : runners are machines where jobs run:
#Types of runners:1)Github_hosted..windows mac os ubuntu are the examples 2)Selft hosted-> Yor server or your cloud virtua machine

#USES ACTION :  
#Actions: Reusable piece of built in fucntion provided by github
#clone->repo
#setu up-> node







  
