name : My First workflow
on   : push
jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello , GitHub Actions!"

  say-bye:
    needs: say-hello
    runs-on: ubuntu-latest

    steps:
      - name: Print message 
        run: echo "Bye , github Actions!!!!"

#   By default jobs run parallely
# To run them in sequence we use needs

  
